---

- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Install HTTPD
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution in ["CentOS"]

    - name: Install APACHE
      apt:
       name: apache2
       state: latest
      when: ansible_distribution in ["Ubuntu"]
