---

- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Install HTTPD & FTP in CentOS
      dnf:
        name:
          - httpd
          - vsftpd
        state: latest
        update_cache: yes
      when: ansible_distribution in ["CentOS"]

    - name: Install APACHE & FTP in Ubuntu
      apt:
       name:
         - apache2
         - vsftpd
       state: latest
       update_cache: yes
      when: ansible_distribution in ["Ubuntu"]
