---
- hosts: all
  become: true
  pre_tasks:
    - name: Install updates(CentOS)
      dnf:
        update_cache: yes
        update_only: yes
      when: ansible_distribution == "CentOS"

    - name: Install updates (Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == "Ubuntu"

- hosts: workers
  become: true
  gather_facts: yes
  tasks:
    - name: Install HTTPD & FTP in CentOS
      dnf:
        name:
          - httpd
          - vsftpd
        state: latest
        update_cache: yes
      when: ansible_distribution in ["CentOS"]

    - name: Install APACHE & FTP in Ubuntu
      apt:
       name:
         - apache2
         - vsftpd
       state: latest
       update_cache: yes
      when: ansible_distribution in ["Ubuntu"]

- hosts: master
  become: true
  tasks:
    - name: Install MYSQLDB server in Master Server
      dnf:
        name: mysql
        state: latest
